tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"
brew "neovim"
brew "node"
cask "font-fira-code"
cask "tor-browser"
cask "visual-studio-code"

