code --install-extension EditorConfig.EditorConfig
code --install-extension mikestead.dotenv
code --install-extension mjmcloug.vscode-elixir
code --install-extension vscodevim.vim
code --install-extension GitHub.vscode-pull-request-github 
code --install-extension felipe.nasc-touchbar
code --install-extension esbenp.prettier-vscode
code --install-extension elmtooling.elm-ls-vscode
code --install-extension johnpapa.vscode-peacock
