# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Erlang and Elixir shell history:
export ERL_AFLAGS="-kernel shell_history enabled"

# Editor:
export EDITOR=$(which nvim)

# Load zsh files
for i in $HOME/.config/zsh/*; do;
    test -r "$i" && source "$i"
done

# look at https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi
